HW4 is completed
seftomsk/go-otus-homework pull request #4
Opened 2021-07-13 07:48 UTC by seftomsk

## Домашнее задание №4 «LRU-кэш»

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [ ] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [ ] Я запустил `go mod tidy`.
- [ ] Я удалил `.sync` файл. [Зачем его удалять?](https://github.com/OtusGolang/home_work/wiki/%5B%D0%A1%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0%D0%BC%5D-%D0%9F%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81-%D1%81%D0%B4%D0%B0%D1%87%D0%B8-%D0%94%D0%97#user-content-%D0%92%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82-2)
- [ ] Я проверил, что все операции выполняются за О(1).

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Добавлены новые юнит-тесты для списка - 1 балл
- [ ] Добавлены новые юнит-тесты для кэша (включая тест на логику
выталкивания из кэша редко используемых элементов) - до 3 баллов
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2021-07-17 03:31 UTC, kulti requested changes
Алексей, спасибо за вариант решения. Хорошее начало, в логике есть ошибки.

Возвращаю на доработку.

Ссылка для преподавателя — https://otus.ru/teacher-lk/homework/8737/10916/

2021-07-17 03:31 UTC, kulti commented on hw04_lru_cache/cache.go
> +		item.Value = cItem
Зачем заменять весь item, если изменилось только value?

2021-07-17 03:31 UTC, kulti commented on hw04_lru_cache/cache.go
> +	if lastItem := cache.queue.Back(); lastItem != nil {
А как он может быть nil? На случай, если capacity будет 0? Но в этом случае кэш же бесполезный будет. Не думаю, что от этого есть смысл защищаться тут. Лучше не разрешать создавать бесполезный кэш.

2021-07-17 03:31 UTC, kulti commented on hw04_lru_cache/cache.go
> +	cache.queue.PushFront(item)
Это не понял. Если взяли элемент из кэша, то почему мы его еще раз кладем на верх списка?

2021-07-17 03:31 UTC, kulti commented on hw04_lru_cache/cache_test.go
> +		c.Clear()
purge logic — это про выталкивание, а не про Clear. То, что лежит в тестах TestCapacityPermission (очень странное название) и TestPushOutOfElements.

2021-07-17 03:31 UTC, kulti commented on hw04_lru_cache/list.go
> +	if i.Prev == nil && i.Next == nil {
Зачем все эти if'чики? Вы поставили галочку «Я перечитал задание после решения». Обратите внимание на жирный текст:
> Гарантируется, что методы Remove и MoveToFront вызываются от существующих в списке элементов.

2021-07-17 03:31 UTC, kulti commented on hw04_lru_cache/list.go
> +	l.count--
Проверки на prev и next получились несимметричные. Тут точно не нужно в if'чик c next добавить код про lastElem?

2021-07-17 03:31 UTC, kulti commented on hw04_lru_cache/list.go
> +	l.lastElem = prevForItem
Что-то тут не то с логикой в этих указателях. MoveToFront передвигает в начало любой элемент из списка, а не только самый последний.

2021-07-17 06:48 UTC, seftomsk commented on hw04_lru_cache/cache.go
> +	cache.queue.PushFront(item)
Так вот же написано в задании:
если элемент присутствует в словаре, то переместить элемент в начало очереди и вернуть его значение и true;
Я тут и перемещаю элемент в начало

2021-07-17 06:56 UTC, seftomsk commented on hw04_lru_cache/cache_test.go
> +		c.Clear()
Я так понимаю, что TestPushOutOfElements и TestCapacityPermission можно запихнуть просто в purge logic?

2021-07-17 06:58 UTC, seftomsk commented on hw04_lru_cache/list.go
> +	if i.Prev == nil && i.Next == nil {
Так гарантируется кем? Если моим кодом, то эти if'ы как раз это и гарантируют, что нельзя передать nil и элемент, который ни к чему не относится. А если гарантируется не моим кодом, то кем?

2021-07-18 07:27 UTC, kulti commented on hw04_lru_cache/cache_test.go
> +		c.Clear()
На ваше усмотрение. Думаю, два отдельных теста тоже хорошо. Тут скорее о термине комментарий, что тест делает не то, что написано.

2021-07-18 07:31 UTC, kulti commented on hw04_lru_cache/list.go
> +	if i.Prev == nil && i.Next == nil {
Гарантируется контрактом использования. Мы можем написать, что этот тип надо использовать так, иначе undefined behaviour (или паника). Суть в том, что не надо усложнять тип список.

Если говорить о проверках, то они не гарантируют, что метод вызван на существующем в списке элементе. Более того, они некорректные. Если в списке один элемент и попробовать его удалить, что произойдет?

2021-07-18 07:39 UTC, kulti commented on hw04_lru_cache/cache.go
> +		capacity = 1
Из каких соображений выбрано значение по умолчанию? Выглядит, как magic number.

Если очень хочется проверить, то можно обозначить контракт, что capacity должно быть больше 0. И тут паниковать.

2021-07-25 06:06 UTC, kulti requested changes
Алексей, осталась одна ошибка.

2021-07-25 06:06 UTC, kulti commented on hw04_lru_cache/list.go
> +	if i.Prev == nil && i.Next == nil {
Еще раз — это некорректная проверка. Если в списке один элемент и попробовать его удалить, что произойдет?

Предлагаю просто считать, что ничего «левого» не передадут (как это и написано в задании), и ничего лишнего не проверять.

2021-08-07 03:19 UTC, kulti approved these changes

2021-11-05 18:23 UTC, merged