HW5 is completed
seftomsk/go-otus-homework pull request #5
Opened 2021-08-02 14:47 UTC by seftomsk

## Домашнее задание №5 «Параллельное исполнение»

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [ ] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [ ] Я запустил `go mod tidy`.
- [ ] Я удалил `.sync` файл. [Зачем его удалять?](https://github.com/OtusGolang/home_work/wiki/%5B%D0%A1%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0%D0%BC%5D-%D0%9F%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81-%D1%81%D0%B4%D0%B0%D1%87%D0%B8-%D0%94%D0%97#user-content-%D0%92%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82-2)
- [ ] Я сравнил объем кода с объемом авторского решения. [Зачем сверять объем кода?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D1%81%D0%B2%D0%B5%D1%80%D1%8F%D1%82%D1%8C-%D0%BE%D0%B1%D1%8A%D0%B5%D0%BC-%D0%BA%D0%BE%D0%B4%D0%B0)
  - run.go ~55 строк

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Добавлены новые юнит-тесты - до 4 баллов
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2021-08-07 03:46 UTC, kulti requested changes
Алексей, спасибо за вариант решения. Должно работать 👍 Немного перегружено получилось местами.

Принято — 9/10.

Ссылка для проверяющего — https://otus.ru/teacher-lk/homework/8737/10927/

2021-08-07 03:46 UTC, kulti commented on hw05_parallel_execution/run.go
> +	go func() {
Эта горутина выглядит лишней. Кажется, можно немного подправить и без нее все получится.

2021-08-07 03:46 UTC, kulti commented on hw05_parallel_execution/run.go
> +				currentTask++
Почему бы не сделать `for _, t := range tasks` вместо бесконечного цикла? Кажется, ничего особо не поменяется, но код станет проще.

2021-08-07 03:46 UTC, kulti commented on hw05_parallel_execution/run_test.go
> +	require.Truef(t, errors.Is(err, ErrErrorsLimitExceeded), "actual error %q", err)
Есть готовая проверка require.ErrorIs.

2021-08-07 03:46 UTC, kulti approved these changes
Извиняюсь, не ту галочку поставил :)

2021-08-09 09:00 UTC, seftomsk commented on hw05_parallel_execution/run.go
> +				currentTask++
Ох, у меня изначально была идея пробегаться по задачам, но что-то я в этом варианте не сообразил совсем... Я подумаю как это сделать

2021-11-05 18:29 UTC, merged